replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.14.2"

service:
  type: NodePort
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
